// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wurhbsbmhxlfupttngfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind1cmhic2JtaHhsZnVwdHRuZ2ZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk3NTUyMjIsImV4cCI6MjA1NTMzMTIyMn0.W-Tqlrhx3HwrUHASCUx2EOGj1Sc8g3KOcCWKgP0rtQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);